"""
state_manager.py - Game State, Crisis Cooldown, Tool-Use History, & HP Engine
Manages 60s session timer, underworld stability HP, and tool verification.
"""

import time
import collections
from typing import List, Dict, Any, Optional
from bridge.sensor_state import SemanticState
from game.schema import Incident


class GameStateManager:
    """
    Core state manager tracking player performance, tool usage history,
    crisis deadlines, and Underworld stability HP.
    """
    STATE_IDLE = "IDLE"
    STATE_PLAYING = "PLAYING"
    STATE_SUCCESS = "SUCCESS"
    STATE_GAME_OVER = "GAME_OVER"

    def __init__(self, session_duration_sec: float = 60.0):
        self.session_duration_sec = session_duration_sec
        self.state = self.STATE_IDLE

        # Timer & Stability HP
        self.time_left = self.session_duration_sec
        self.stability_hp = 100.0
        self.score = 0
        self.combo = 0
        self.current_round = 0

        # Tool history (rolling window for prompt context)
        self.tool_history = collections.deque(maxlen=6)

        # Active Crisis
        self.active_incident: Optional[Incident] = None
        self.incident_start_time = 0.0
        self.incident_deadline = 0.0
        self.last_crisis_resolved_time = 0.0

        # Crisis resolution transition timer
        self.success_display_timer = 0.0
        self.last_update_time = time.time()

    def start_game(self):
        """Starts a fresh Underworld guard session."""
        self.state = self.STATE_PLAYING
        self.time_left = self.session_duration_sec
        self.stability_hp = 100.0
        self.score = 0
        self.combo = 0
        self.current_round = 0
        self.tool_history.clear()
        self.active_incident = None
        self.last_update_time = time.time()
        print("[GameStateManager] Game session started.")

    def set_new_incident(self, incident: Incident):
        """Assigns a new crisis generated by Gemini AI."""
        self.active_incident = incident
        self.current_round += 1
        now = time.time()
        self.incident_start_time = now
        self.incident_deadline = now + incident.time_limit_sec
        self.state = self.STATE_PLAYING
        print(f"[GameStateManager] New Crisis: {incident.incident_title} | Target: {incident.target_tool} ({incident.time_limit_sec}s)")

    def get_tool_history_str(self) -> str:
        """Formats recent tools into prompt string."""
        if not self.tool_history:
            return "None"
        return ", ".join(list(self.tool_history)[-4:])

    def update(self, semantic_state: SemanticState) -> Dict[str, Any]:
        """
        Updates session clock and checks if player's physical action
        resolves the active crisis. Returns event dict.
        """
        now = time.time()
        dt = max(0.001, now - self.last_update_time)
        self.last_update_time = now

        events = {
            "action_succeeded": False,
            "crisis_failed": False,
            "game_over": False,
            "needs_new_incident": False
        }

        # Check physical button for round restart if in IDLE / GAME_OVER
        if semantic_state.switch_on and self.state in [self.STATE_IDLE, self.STATE_GAME_OVER]:
            self.start_game()
            events["needs_new_incident"] = True
            return events

        if self.state == self.STATE_IDLE:
            return events

        if self.state == self.STATE_SUCCESS:
            self.success_display_timer -= dt
            if self.success_display_timer <= 0.0:
                self.state = self.STATE_PLAYING
                events["needs_new_incident"] = True
            return events

        if self.state == self.STATE_PLAYING:
            # Decrement session timer
            self.time_left = max(0.0, self.time_left - dt)
            self.stability_hp = max(0.0, min(100.0, (self.time_left / self.session_duration_sec) * 100.0))

            if self.time_left <= 0.0:
                self.state = self.STATE_GAME_OVER
                events["game_over"] = True
                print(f"[GameStateManager] Time Expired! Final Score: {self.score}")
                return events

            if not self.active_incident:
                events["needs_new_incident"] = True
                return events

            # Check if active crisis is satisfied by physical sensors
            is_satisfied = self._evaluate_action(self.active_incident, semantic_state)
            if is_satisfied:
                self._handle_success(self.active_incident)
                events["action_succeeded"] = True
                return events

            # Check if crisis time limit expired
            if now >= self.incident_deadline:
                self._handle_failure(self.active_incident)
                events["crisis_failed"] = True
                events["needs_new_incident"] = True
                return events

        return events

    def _evaluate_action(self, incident: Incident, state: SemanticState) -> bool:
        """Verifies if the player's physical state matches the required tool."""
        req_tool = incident.target_tool.upper()

        if req_tool == "TOOL_BLOW":
            return state.is_blowing
        elif req_tool == "TOOL_LIGHT":
            return state.light_pct < 25.0  # Covered / Shaded
        elif req_tool == "TOOL_GATE":
            return state.gate_angle > 65.0 # Locked gate
        elif req_tool == "TOOL_VOICE":
            return state.is_voice_active   # Microphone chant
        return False

    def _handle_success(self, incident: Incident):
        self.state = self.STATE_SUCCESS
        self.success_display_timer = 1.2
        self.combo += 1
        points = 100 + (self.combo * 25)
        self.score += points
        self.tool_history.append(incident.target_tool)
        self.last_crisis_resolved_time = time.time()
        print(f"[GameStateManager] SUCCESS! Resolved: {incident.incident_title} (+{points} pts | Combo: {self.combo}x)")

    def _handle_failure(self, incident: Incident):
        self.combo = 0
        self.stability_hp = max(0.0, self.stability_hp - 15.0)
        self.tool_history.append(f"{incident.target_tool}_FAILED")
        print(f"[GameStateManager] FAILED: {incident.incident_title} (Time limit expired!)")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "state": self.state,
            "time_left": round(self.time_left, 1),
            "stability_hp": round(self.stability_hp, 1),
            "score": self.score,
            "combo": self.combo,
            "current_round": self.current_round,
            "tool_history": list(self.tool_history),
            "active_incident": self.active_incident.to_dict() if self.active_incident else None
        }
